server:
  port: ${PORT:0}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-alumnos

  datasource:
    url: jdbc:postgresql://localhost:5432/db_ms_alumnos
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQL10Dialect
  jackson:
    time-zone: America/Mexico_City
    locale: es_MX

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  logging:
    level:
      org:
        hibernate:
          SQL: debug
